module FPSCorba{
	interface Listener{
		string healthUpdate();
		string selectWeapon();
	};
	interface Server{
		void updateTables();
		void requestConnect(in Listener l);
		void sendPools();
		void removeWeapon(); //This will be sendPools() with weapons removed
		void sendWeapon();
		void sendShield();
		void announceWinner();
	};
};