package FPSCorba;


/**
* FPSCorba/ListenerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from fpscorba.idl
* Tuesday, May 6, 2014 11:33:58 AM EDT
*/

public abstract class ListenerPOA extends org.omg.PortableServer.Servant
 implements FPSCorba.ListenerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("healthUpdate", new java.lang.Integer (0));
    _methods.put ("selectWeapon", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // FPSCorba/Listener/healthUpdate
       {
         String $result = null;
         $result = this.healthUpdate ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // FPSCorba/Listener/selectWeapon
       {
         String $result = null;
         $result = this.selectWeapon ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:FPSCorba/Listener:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Listener _this() 
  {
    return ListenerHelper.narrow(
    super._this_object());
  }

  public Listener _this(org.omg.CORBA.ORB orb) 
  {
    return ListenerHelper.narrow(
    super._this_object(orb));
  }


} // class ListenerPOA
