package FPSCorba;


/**
* FPSCorba/ListenerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from fpscorba.idl
* Tuesday, May 6, 2014 11:33:58 AM EDT
*/

public interface ListenerOperations 
{
  String healthUpdate ();
  String selectWeapon ();
} // interface ListenerOperations
