package FPSCorba;

/**
* FPSCorba/ListenerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from fpscorba.idl
* Tuesday, May 6, 2014 11:33:58 AM EDT
*/

public final class ListenerHolder implements org.omg.CORBA.portable.Streamable
{
  public FPSCorba.Listener value = null;

  public ListenerHolder ()
  {
  }

  public ListenerHolder (FPSCorba.Listener initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FPSCorba.ListenerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FPSCorba.ListenerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FPSCorba.ListenerHelper.type ();
  }

}
