package FPSCorba;

/**
* FPSCorba/ServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from fpscorba.idl
* Tuesday, May 6, 2014 11:33:58 AM EDT
*/

public final class ServerHolder implements org.omg.CORBA.portable.Streamable
{
  public FPSCorba.Server value = null;

  public ServerHolder ()
  {
  }

  public ServerHolder (FPSCorba.Server initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FPSCorba.ServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FPSCorba.ServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FPSCorba.ServerHelper.type ();
  }

}
