package FPSCorba;


/**
* FPSCorba/ServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from fpscorba.idl
* Tuesday, May 6, 2014 11:33:58 AM EDT
*/

public interface ServerOperations 
{
  void updateTables ();
  void requestConnect (FPSCorba.Listener l);
  void sendPools ();
  void removeWeapon ();

  //This will be sendPools() with weapons removed
  void sendWeapon ();
  void sendShield ();
  void announceWinner ();
} // interface ServerOperations
