package FPSCorba;


/**
* FPSCorba/ServerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from fpscorba.idl
* Tuesday, May 6, 2014 11:33:58 AM EDT
*/

abstract public class ServerHelper
{
  private static String  _id = "IDL:FPSCorba/Server:1.0";

  public static void insert (org.omg.CORBA.Any a, FPSCorba.Server that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static FPSCorba.Server extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (FPSCorba.ServerHelper.id (), "Server");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static FPSCorba.Server read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ServerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, FPSCorba.Server value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static FPSCorba.Server narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof FPSCorba.Server)
      return (FPSCorba.Server)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      FPSCorba._ServerStub stub = new FPSCorba._ServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static FPSCorba.Server unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof FPSCorba.Server)
      return (FPSCorba.Server)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      FPSCorba._ServerStub stub = new FPSCorba._ServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
